### ISSUE TITLE
heavy validation webhook

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/hierarchical-namespaces#352] opened 2024-01-15 21:45 UTC
sometimes we have problems with the worker nodes or network problems, and in the end result the hnc pods are not running (we do use ha),
and since there is [this heavy webhook](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/config/webhook/manifests.yaml#L81-L93) we basically cant do anything on the cluster because it requires to validate almost every api request, thus preventing us from fixing the cluster so we need to delete the webhook and deal with the hnc first.

im not sure why the validation webhook has `*` but i was wondering isn't its better to run the hnc pods on the master nodes?
then hnc and api can go together, if api is available than probably hnc as well.

**Comment by erikgb** [comment] 2024-03-10 11:16
Will be fixed by https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/285.

Duplicate of https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/152

/close

**Closed by erikgb** 2024-03-10 11:16 UTC
