### ISSUE TITLE
Getting error "tls.crt: no such file or directory" when building HNC from main branch

### ISSUE THREAD

**Issue by jvaibhav123** [kubernetes-sigs/hierarchical-namespaces#158] opened 2022-03-23 09:54 UTC
Hi,

Environment details:
Rancher: 2.6.2
k8s cluster: EKS
k8s version: v1.21.5

We tried to generate manifests and image by building source from main branch. We were able to do that. However , when we deploy the manifests, we were getting error 
```
"msg":"problem running manager","error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:255" 
```
The similar issue was mentioned https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/139#issuecomment-1036615144.

We would like to use HNC feature of label and annotation propagation and require to fix above error. It would be great if you could elaborate to set up the certificates using cert manager. We do have cert manager installed in our environment.

Thanks in advance.

**Comment by erikgb** [comment] 2022-03-23 20:04
I was experiencing the same issue when working on #139, and I am now unable get the HNC controller pod ready to run e2e-tests - after it got merged. 😒 @adrianludwin, maybe #139 should be reverted? At least until we are able to find the root cause for this issue. I find it hard to believe that the k8s distro is to blame for this, but I am also using a Rancher-based distro (k3s 1.23).

IMO we should have better support for cert-manager in HNC, preferably have cert-manager as the default - with an opt-in using cert-controller. It requires an extra component in your cluster, which [cert-controller](https://github.com/open-policy-agent/cert-controller) doesn't, but cert-manager is like "bread and butter" for k8s nowadays....

**Comment by adrianludwin** [comment] 2022-03-24 01:08
Ok, I'm not certain what's going on but let's revert #139. And we can try again later.

cert-controller is easy to disable by removing `--enable-internal-cert-management` from the manifest. cert-manager _used_ to be supported by default but it's now commented out [here](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/a34e5767c95fadfee51dd4e0aab23aa4c80d6677/config/default/kustomization.yaml#L20). Perhaps we could find some way to build both manifests as part of our regular release?

**Comment by adrianludwin** [comment] 2022-03-24 01:37
I'm also seeing that the postsubmits and periodics have been failing since #139 was merged on March 16. So weird that I'm not seeing the problem on GKE :( https://testgrid.k8s.io/wg-multi-tenancy-hnc#periodic-e2e-tests&width=90

**Comment by adrianludwin** [comment] 2022-03-24 01:48
Ok, I've finally reproduced this problem on GKE. It was pretty dumb of me not to realize: if HNC is _fully_ uninstalled, I can recreate the problem, but if the Secret from a prior installation is still there, everything's able to start up successfully.

I'm going to see if I can fix this before reverting, I suspect it might have to have something to do with the start order.

**Comment by adrianludwin** [comment] 2022-03-24 03:34
/cc @erikgb 

Ok, I finally understand the problem. The new `setupChecks()` function registers the health checks by calling `mgr.GetWebhookServer().StartedChecker()`, but unfortunately `GetWebhookServer()` actually _starts_ a webhook server if one wasn't started already.

Before this change, HNC carefully did _not_ create any webhooks until _after_ the cert controller finished creating the secret that actually contains the certs, but this change breaks that assumption and tries to start the webhook server immediately simply to run the health probes. However, since the secret doesn't exist, the server fails to start, killing the entire process.

Currently thinking about how to solve this.

**Comment by adrianludwin** [comment] 2022-03-24 03:52
This is easy to fix since we have access to `certsReady` which tells us if it's safe to start the webhook server. PR ready shortly.

**Closed** 2022-03-24 09:24 UTC
